const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const messages=$('#messages');const input=$('#messageInput');const toast=$('#toast');const modal=$('#modal');let currentServer='Drax';
function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
$$('.channel[data-channel]').forEach(c=>c.onclick=()=>{ $$('.channel').forEach(x=>x.classList.remove('active-channel'));c.classList.add('active-channel');const n=c.dataset.channel;$('#channelName').textContent=n;input.placeholder=`Enviar mensagem em #${n}`;$('.welcome h1').textContent=`Bem-vindo ao #${n}!`;showToast(`Canal #${n} selecionado`) });
$$('.server[data-server]').forEach(s=>s.onclick=()=>{$$('.server').forEach(x=>x.classList.remove('active'));s.classList.add('active');currentServer=s.dataset.server;$('#serverName').textContent=currentServer;showToast(`Servidor ${currentServer}`)});
$('#composer').onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;const article=document.createElement('article');article.className='message';article.innerHTML=`<div class="avatar blue">A</div><div><div class="meta"><strong>Arthur</strong><span>agora</span></div><p></p></div>`;article.querySelector('p').textContent=text;messages.appendChild(article);input.value='';messages.scrollTop=messages.scrollHeight};
$('#emoji').onclick=()=>{input.value+=' 😊';input.focus()};$('#attach').onclick=()=>showToast('Anexos: demonstração local');$('#mic').onclick=()=>showToast('Microfone alternado');$('#bell').onclick=()=>showToast('Notificações alternadas');$('#membersBtn').onclick=()=>$('#members').classList.toggle('hidden-mobile');$('#theme').onclick=()=>{document.body.classList.toggle('light');showToast('Tema alternado')};$('#settings').onclick=()=>showToast('Configurações da conta');$('#explore').onclick=()=>showToast('Explorar servidores');
$('#search').oninput=e=>{$$('.message').forEach(m=>m.style.display=(!e.target.value||m.textContent.toLowerCase().includes(e.target.value.toLowerCase()))?'flex':'none')};
$('#addServer').onclick=()=>{modal.classList.remove('hidden');$('#modalInput').focus()};$('#closeModal').onclick=()=>modal.classList.add('hidden');$('#modalConfirm').onclick=()=>{const n=$('#modalInput').value.trim();if(!n)return;const b=document.createElement('button');b.className='server';b.dataset.server=n;b.innerHTML=`<span>${n[0].toUpperCase()}</span>`;b.onclick=()=>{ $$('.server').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#serverName').textContent=n;showToast(`Servidor ${n}`)};$('.servers').insertBefore(b,$('#addServer'));$('#modalInput').value='';modal.classList.add('hidden');b.click()};
$('#serverMenu').onclick=()=>showToast(`${currentServer}: menu do servidor`);document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.add('hidden')});
